name: move_to_signal
description: Import messages from other apps like WhatsApp to Signal.
version: 1.3.0
repository: https://github.com/de-nets/MoveToSignal

environment:
  sdk: ^3.1.0

dependencies:
  intl: ^0.20.0
  path: ^1.9.1
  sqlite3: ^2.7.5
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
