name: move_to_signal
description: Import messages from other apps like WhatsApp to Signal.
version: 1.2.0
repository: https://github.com/de-nets/MoveToSignal

environment:
  sdk: ^3.1.0

dependencies:
  intl: ^0.19.0
  path: ^1.8.3
  sqlite3: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
